In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('/content/hepatitis.csv')
df

2  30  2.1  1  2.2 2.3 2.4 2.5 1.1 2.6 2.7 2.8 2.9 2.10  1.00   85   18  \
0    2  50    1  1    2   1   2   2   1   2   2   2   2    2  0.90  135   42   
1    2  78    1  2    2   1   2   2   2   2   2   2   2    2  0.70   96   32   
2    2  31    1  ?    1   2   2   2   2   2   2   2   2    2  0.70   46   52   
3    2  34    1  2    2   2   2   2   2   2   2   2   2    2  1.00    ?  200   
4    2  34    1  2    2   2   2   2   2   2   2   2   2    2  0.90   95   28   
..  ..  ..  ... ..  ...  ..  ..  ..  ..  ..  ..  ..  ..  ...   ...  ...  ...   
149  1  46    1  2    2   1   1   1   2   2   2   1   1    1  7.60    ?  242   
150  2  44    1  2    2   1   2   2   2   1   2   2   2    2  0.90  126  142   
151  2  61    1  1    2   1   1   2   1   1   2   1   2    2  0.80   75   20   
152  2  53    2  1    2   1   2   2   2   2   1   1   2    1  1.50   81   19   
153  1  43    1  2    2   1   2   2   2   2   1   1   1    2  1.20  100   19   

     4.0   ?  1.2  
0    3.5   ?    1  
1    4.0   ?    1  
2    4.0  80    1  
3    4.0   ?    1  
4    4.0  75    1  
..   ...  ..  ...  
149  3.3  50    2  
150  4.3   ?    2  
151  4.1   ?    2  
152  4.1  48    2  
153  3.1  42    2  

[154 rows x 20 columns]

In [3]:
df.columns = ['Class', 'AGE', 'SEX', 'STEROID', 'ANTIVIRALS', 'FATIGUE',
              'MALAISE', 'ANOREXIA', 'LIVER_BIG', 'LIVER_FIRM',
              'SPLEEN_PALPABLE', 'SPIDERS', 'ASCITES', 'VARICES',
              'BILIRUBIN', 'ALK_PHOSPHATE', 'SGOT', 'ALBUMIN',
              'PROTIME', 'HISTOLOGY']

df.head(10)

Class  AGE  SEX STEROID  ANTIVIRALS FATIGUE MALAISE ANOREXIA LIVER_BIG  \
0      2   50    1       1           2       1       2        2         1   
1      2   78    1       2           2       1       2        2         2   
2      2   31    1       ?           1       2       2        2         2   
3      2   34    1       2           2       2       2        2         2   
4      2   34    1       2           2       2       2        2         2   
5      1   51    1       1           2       1       2        1         2   
6      2   23    1       2           2       2       2        2         2   
7      2   39    1       2           2       1       2        2         2   
8      2   30    1       2           2       2       2        2         2   
9      2   39    1       1           1       2       2        2         1   

  LIVER_FIRM SPLEEN_PALPABLE SPIDERS ASCITES VARICES BILIRUBIN ALK_PHOSPHATE  \
0          2               2       2       2       2      0.90           135   
1          2               2       2       2       2      0.70            96   
2          2               2       2       2       2      0.70            46   
3          2               2       2       2       2      1.00             ?   
4          2               2       2       2       2      0.90            95   
5          2               1       1       2       2         ?             ?   
6          2               2       2       2       2      1.00             ?   
7          1               2       2       2       2      0.70             ?   
8          2               2       2       2       2      1.00             ?   
9          1               2       2       2       2      1.30            78   

  SGOT ALBUMIN PROTIME  HISTOLOGY  
0   42     3.5       ?          1  
1   32     4.0       ?          1  
2   52     4.0      80          1  
3  200     4.0       ?          1  
4   28     4.0      75          1  
5    ?       ?       ?          1  
6    ?       ?       ?          1  
7   48     4.4       ?          1  
8  120     3.9       ?          1  
9   30     4.4      85          1

# CLASS COLUMN


In [4]:
df['Class'].unique()

array([2, 1])

In [5]:
df['Class'] = pd.to_numeric(df['Class'], errors='coerce').fillna(0).astype(int)
df['Class'].dtype

dtype('int64')

In [6]:
occurrences = df['Class'].value_counts().get(1, 0)
occurrences

32

In [7]:
df['Class'] = df['Class'].astype(str)
df['Class'].dtype

dtype('O')

In [8]:
df['Class'] = df['Class'].replace('1', 'DIE')
df['Class'].unique()

array(['2', 'DIE'], dtype=object)

In [9]:
df['Class'] = df['Class'].replace('2', 'LIVE')
df['Class'].unique()

array(['LIVE', 'DIE'], dtype=object)

# SEX COLUMN


In [10]:
df['SEX'].unique()

array([1, 2])

In [11]:
df['SEX'].dtype

dtype('int64')

In [12]:
df['SEX'] = df['SEX'].astype(str)
df['SEX'].dtype

dtype('O')

In [13]:
df['SEX'] = df['SEX'].replace('1', 'male')
df['SEX'] = df['SEX'].replace('2', 'female')
df['SEX'].unique()

array(['male', 'female'], dtype=object)

# STEROID


In [14]:
df['STEROID'].unique()

array(['1', '2', '?'], dtype=object)

In [15]:
df['STEROID'] = df['STEROID'].replace('1', 'no')
df['STEROID'] = df['STEROID'].replace('2', 'yes')
df['STEROID'].unique()

array(['no', 'yes', '?'], dtype=object)

# REPLACING THE '?' WITH THE MODE IN STEROID COLUMN



In [16]:
# Replace '?' with mode
mode_value = df['STEROID'].mode()[0]  # Calculate mode
df['STEROID'] = df['STEROID'].replace('?', mode_value)

In [17]:
df['STEROID'].unique()

array(['no', 'yes'], dtype=object)

#ANTIVIRALS COLUMN

In [18]:
df['ANTIVIRALS'].unique()


array([2, 1])

In [19]:
df['ANTIVIRALS'].dtype

dtype('int64')

In [20]:
df['ANTIVIRALS'] = df['ANTIVIRALS'].astype(str)
df['ANTIVIRALS'].dtype

dtype('O')

In [21]:
df['ANTIVIRALS'] = df['ANTIVIRALS'].replace('1', 'no')
df['ANTIVIRALS'] = df['ANTIVIRALS'].replace('2', 'yes')
df['ANTIVIRALS'].unique()

array(['yes', 'no'], dtype=object)

# FATIGUE COLUMN

In [22]:
df['FATIGUE'].unique()


array(['1', '2', '?'], dtype=object)

In [23]:
df['FATIGUE'] = df['FATIGUE'].replace('1', 'no')
df['FATIGUE'] = df['FATIGUE'].replace('2', 'yes')
df['FATIGUE'].unique()

array(['no', 'yes', '?'], dtype=object)

# MALAISE COLUMN

In [24]:
df['MALAISE'].unique()


array(['2', '1', '?'], dtype=object)

In [25]:
df['MALAISE'] = df['MALAISE'].replace('1', 'no')
df['MALAISE'] = df['MALAISE'].replace('2', 'yes')
df['MALAISE'].unique()

array(['yes', 'no', '?'], dtype=object)

In [26]:
# Replace '?' with mode
mode_value = df['MALAISE'].mode()[0]  # Calculate mode
df['MALAISE'] = df['MALAISE'].replace('?', mode_value)

In [27]:
df['MALAISE'].unique()


array(['yes', 'no'], dtype=object)

# ANOREXIA COLUMN

In [28]:
df['ANOREXIA'].unique()

array(['2', '1', '?'], dtype=object)

In [29]:
df['ANOREXIA'] = df['ANOREXIA'].replace('1', 'no')
df['ANOREXIA'] = df['ANOREXIA'].replace('2', 'yes')
df['ANOREXIA'].unique()

array(['yes', 'no', '?'], dtype=object)

In [30]:
# Replace '?' with mode
mode_value = df['ANOREXIA'].mode()[0]  # Calculate mode
df['ANOREXIA'] = df['ANOREXIA'].replace('?', mode_value)
df['ANOREXIA'].unique()

array(['yes', 'no'], dtype=object)

# LIVER BIG COLUMN

In [31]:
df['LIVER_BIG'].unique()

array(['1', '2', '?'], dtype=object)

In [32]:
df['LIVER_BIG'] = df['LIVER_BIG'].replace('1', 'no')
df['LIVER_BIG'] = df['LIVER_BIG'].replace('2', 'yes')
df['LIVER_BIG'].unique()

array(['no', 'yes', '?'], dtype=object)

In [33]:
# Replace '?' with mode
mode_value = df['LIVER_BIG'].mode()[0]  # Calculate mode
df['LIVER_BIG'] = df['LIVER_BIG'].replace('?', mode_value)
df['LIVER_BIG'].unique()

array(['no', 'yes'], dtype=object)

# LIVER FIRM COLUMN

In [34]:
df['LIVER_FIRM'].unique()

array(['2', '1', '?'], dtype=object)

In [35]:
df['LIVER_FIRM'] = df['LIVER_FIRM'].replace('1', 'no')
df['LIVER_FIRM'] = df['LIVER_FIRM'].replace('2', 'yes')
df['LIVER_FIRM'].unique()

array(['yes', 'no', '?'], dtype=object)

In [36]:
# Replace '?' with mode
mode_value = df['LIVER_FIRM'].mode()[0]  # Calculate mode
df['LIVER_FIRM'] = df['LIVER_FIRM'].replace('?', mode_value)
df['LIVER_FIRM'].unique()

array(['yes', 'no'], dtype=object)

# SPLEEN PALPABLE COLUMN

In [37]:
df['SPLEEN_PALPABLE'].unique()

array(['2', '1', '?'], dtype=object)

In [38]:
df['SPLEEN_PALPABLE'] = df['SPLEEN_PALPABLE'].replace('1', 'no')
df['SPLEEN_PALPABLE'] = df['SPLEEN_PALPABLE'].replace('2', 'yes')
df['SPLEEN_PALPABLE'].unique()

array(['yes', 'no', '?'], dtype=object)

In [39]:
# Replace '?' with mode
mode_value = df['SPLEEN_PALPABLE'].mode()[0]  # Calculate mode
df['SPLEEN_PALPABLE'] = df['SPLEEN_PALPABLE'].replace('?', mode_value)
df['SPLEEN_PALPABLE'].unique()

array(['yes', 'no'], dtype=object)

# SPIDERS COLUMN

In [40]:
df['SPIDERS'].unique()

array(['2', '1', '?'], dtype=object)

In [41]:
df['SPIDERS'] = df['SPIDERS'].replace('1', 'no')
df['SPIDERS'] = df['SPIDERS'].replace('2', 'yes')
df['SPIDERS'].unique()

array(['yes', 'no', '?'], dtype=object)

In [42]:
# Replace '?' with mode
mode_value = df['SPIDERS'].mode()[0]  # Calculate mode
df['SPIDERS'] = df['SPIDERS'].replace('?', mode_value)
df['SPIDERS'].unique()

array(['yes', 'no'], dtype=object)

# ASCITES COLUMN

In [43]:
df['ASCITES'].unique()

array(['2', '1', '?'], dtype=object)

In [44]:
df['ASCITES'] = df['ASCITES'].replace('1', 'no')
df['ASCITES'] = df['ASCITES'].replace('2', 'yes')
df['ASCITES'].unique()

array(['yes', 'no', '?'], dtype=object)

In [45]:
# Replace '?' with mode
mode_value = df['ASCITES'].mode()[0]  # Calculate mode
df['ASCITES'] = df['ASCITES'].replace('?', mode_value)
df['ASCITES'].unique()

array(['yes', 'no'], dtype=object)

# Varice COLUMN

In [46]:
df.columns

Index(['Class', 'AGE', 'SEX', 'STEROID', 'ANTIVIRALS', 'FATIGUE', 'MALAISE',
       'ANOREXIA', 'LIVER_BIG', 'LIVER_FIRM', 'SPLEEN_PALPABLE', 'SPIDERS',
       'ASCITES', 'VARICES', 'BILIRUBIN', 'ALK_PHOSPHATE', 'SGOT', 'ALBUMIN',
       'PROTIME', 'HISTOLOGY'],
      dtype='object')

In [47]:
df['VARICES'].unique()

array(['2', '?', '1'], dtype=object)

In [48]:
df['VARICES'] = pd.to_numeric(df['VARICES'], errors='coerce')
df['VARICES'].dtype

dtype('float64')

In [49]:
df['VARICES'].unique()

array([ 2., nan,  1.])

In [50]:
mode_value = df['VARICES'].mode()[0]
df['VARICES'] = df['VARICES'].fillna(mode_value)

In [51]:
df['VARICES'].unique()

array([2., 1.])

In [52]:
df.columns

Index(['Class', 'AGE', 'SEX', 'STEROID', 'ANTIVIRALS', 'FATIGUE', 'MALAISE',
       'ANOREXIA', 'LIVER_BIG', 'LIVER_FIRM', 'SPLEEN_PALPABLE', 'SPIDERS',
       'ASCITES', 'VARICES', 'BILIRUBIN', 'ALK_PHOSPHATE', 'SGOT', 'ALBUMIN',
       'PROTIME', 'HISTOLOGY'],
      dtype='object')

#BILIRUBIN column

In [53]:
df['BILIRUBIN'].unique()

array(['0.90', '0.70', '1.00', '?', '1.30', '2.20', '2.00', '1.20',
       '0.60', '0.40', '0.80', '1.40', '2.30', '0.50', '0.30', '4.60',
       '1.80', '3.50', '4.10', '1.60', '2.80', '1.50', '2.50', '3.00',
       '4.80', '2.40', '1.70', '1.10', '3.20', '2.90', '8.00', '3.90',
       '1.90', '4.20', '7.60'], dtype=object)

In [54]:
df['BILIRUBIN'] = pd.to_numeric(df['BILIRUBIN'], errors='coerce')
df['BILIRUBIN'].dtype

dtype('float64')

In [55]:
mean_value = df['BILIRUBIN'].mean()
df['BILIRUBIN'] = df['BILIRUBIN'].fillna(mean_value)

# ALK_PHOSPHATE column

In [56]:
df['ALK_PHOSPHATE'].unique()

array(['135', '96', '46', '?', '95', '78', '59', '81', '57', '72', '102',
       '62', '53', '70', '48', '133', '85', '60', '45', '175', '280',
       '58', '67', '194', '150', '180', '75', '56', '71', '74', '80',
       '191', '125', '110', '50', '92', '52', '26', '215', '164', '103',
       '34', '68', '82', '127', '76', '100', '55', '167', '30', '179',
       '141', '44', '165', '118', '230', '107', '40', '147', '114', '84',
       '123', '168', '86', '138', '155', '63', '256', '119', '139', '90',
       '160', '158', '115', '243', '181', '130', '166', '295', '120',
       '65', '109', '89', '126'], dtype=object)

In [57]:
df['ALK_PHOSPHATE'] = pd.to_numeric(df['ALK_PHOSPHATE'], errors='coerce')
df['ALK_PHOSPHATE'].dtype

dtype('float64')

In [58]:
df['ALK_PHOSPHATE'].unique()

array([135.,  96.,  46.,  nan,  95.,  78.,  59.,  81.,  57.,  72., 102.,
        62.,  53.,  70.,  48., 133.,  85.,  60.,  45., 175., 280.,  58.,
        67., 194., 150., 180.,  75.,  56.,  71.,  74.,  80., 191., 125.,
       110.,  50.,  92.,  52.,  26., 215., 164., 103.,  34.,  68.,  82.,
       127.,  76., 100.,  55., 167.,  30., 179., 141.,  44., 165., 118.,
       230., 107.,  40., 147., 114.,  84., 123., 168.,  86., 138., 155.,
        63., 256., 119., 139.,  90., 160., 158., 115., 243., 181., 130.,
       166., 295., 120.,  65., 109.,  89., 126.])

In [59]:
median_value = df['ALK_PHOSPHATE'].median()
df['ALK_PHOSPHATE'] = df['ALK_PHOSPHATE'].fillna(median_value)

In [60]:
df['ALK_PHOSPHATE'].unique()

array([135.,  96.,  46.,  85.,  95.,  78.,  59.,  81.,  57.,  72., 102.,
        62.,  53.,  70.,  48., 133.,  60.,  45., 175., 280.,  58.,  67.,
       194., 150., 180.,  75.,  56.,  71.,  74.,  80., 191., 125., 110.,
        50.,  92.,  52.,  26., 215., 164., 103.,  34.,  68.,  82., 127.,
        76., 100.,  55., 167.,  30., 179., 141.,  44., 165., 118., 230.,
       107.,  40., 147., 114.,  84., 123., 168.,  86., 138., 155.,  63.,
       256., 119., 139.,  90., 160., 158., 115., 243., 181., 130., 166.,
       295., 120.,  65., 109.,  89., 126.])

# SGOT COLUMN

In [61]:
df['SGOT'].unique()

array(['42', '32', '52', '200', '28', '?', '48', '120', '30', '249', '60',
       '144', '89', '53', '166', '20', '98', '63', '18', '46', '55', '25',
       '58', '29', '92', '150', '68', '14', '16', '90', '86', '110', '80',
       '420', '44', '65', '145', '31', '78', '59', '38', '75', '64', '54',
       '43', '33', '15', '39', '182', '271', '45', '100', '242', '24',
       '224', '69', '156', '123', '117', '157', '128', '23', '40', '227',
       '269', '34', '648', '225', '136', '81', '153', '118', '231', '101',
       '278', '49', '181', '140', '70', '114', '173', '528', '152', '142',
       '19'], dtype=object)

In [62]:
df['SGOT'] = pd.to_numeric(df['SGOT'], errors='coerce')
df['SGOT'].dtype

dtype('float64')

In [63]:
mean_value = df['SGOT'].mean()  # Calculate mode
mean_value

86.34666666666666

In [64]:
# Replace '?' with mode
mean_value = df['SGOT'].mean()  # Calculate mode
df['SGOT'] = df['SGOT'].replace('?', mean_value)
df['SGOT'].unique()

array([ 42.,  32.,  52., 200.,  28.,  nan,  48., 120.,  30., 249.,  60.,
       144.,  89.,  53., 166.,  20.,  98.,  63.,  18.,  46.,  55.,  25.,
        58.,  29.,  92., 150.,  68.,  14.,  16.,  90.,  86., 110.,  80.,
       420.,  44.,  65., 145.,  31.,  78.,  59.,  38.,  75.,  64.,  54.,
        43.,  33.,  15.,  39., 182., 271.,  45., 100., 242.,  24., 224.,
        69., 156., 123., 117., 157., 128.,  23.,  40., 227., 269.,  34.,
       648., 225., 136.,  81., 153., 118., 231., 101., 278.,  49., 181.,
       140.,  70., 114., 173., 528., 152., 142.,  19.])

In [65]:
df['SGOT']

0       42.0
1       32.0
2       52.0
3      200.0
4       28.0
       ...  
149    242.0
150    142.0
151     20.0
152     19.0
153     19.0
Name: SGOT, Length: 154, dtype: float64

# ALBUMIN COLUMN

In [66]:
df['ALBUMIN'].unique()

array(['3.5', '4.0', '?', '4.4', '3.9', '3.7', '4.9', '2.9', '4.3', '4.1',
       '4.2', '4.7', '3.8', '2.7', '4.6', '5.0', '3.3', '4.5', '3.4',
       '3.1', '3.0', '2.6', '5.3', '4.8', '2.8', '3.6', '2.1', '6.4',
       '2.4', '2.2'], dtype=object)

In [67]:
df['ALBUMIN'] = pd.to_numeric(df['ALBUMIN'], errors='coerce')
df['ALBUMIN'].dtype

dtype('float64')

In [68]:
# Replace '?' with mode
mean_value = df['ALBUMIN'].mean()  # Calculate mode
df['ALBUMIN'] = df['ALBUMIN'].replace('?', mean_value)
df['ALBUMIN'].unique()

array([3.5, 4. , nan, 4.4, 3.9, 3.7, 4.9, 2.9, 4.3, 4.1, 4.2, 4.7, 3.8,
       2.7, 4.6, 5. , 3.3, 4.5, 3.4, 3.1, 3. , 2.6, 5.3, 4.8, 2.8, 3.6,
       2.1, 6.4, 2.4, 2.2])

In [69]:
df.isnull().sum()

Class               0
AGE                 0
SEX                 0
STEROID             0
ANTIVIRALS          0
FATIGUE             0
MALAISE             0
ANOREXIA            0
LIVER_BIG           0
LIVER_FIRM          0
SPLEEN_PALPABLE     0
SPIDERS             0
ASCITES             0
VARICES             0
BILIRUBIN           0
ALK_PHOSPHATE       0
SGOT                4
ALBUMIN            16
PROTIME             0
HISTOLOGY           0
dtype: int64

# PROTIME COLUMN

In [70]:
df['PROTIME'].unique()

array(['?', '80', '75', '85', '54', '52', '78', '46', '63', '62', '64',
       '39', '100', '47', '70', '36', '40', '74', '60', '73', '90', '21',
       '77', '29', '41', '66', '57', '56', '76', '58', '84', '38', '67',
       '31', '51', '23', '72', '32', '30', '0', '50', '43', '35', '48',
       '42'], dtype=object)

In [71]:
df['PROTIME'] = pd.to_numeric(df['PROTIME'], errors='coerce')
df['PROTIME'].dtype

dtype('float64')

In [72]:
df['PROTIME'].unique()

array([ nan,  80.,  75.,  85.,  54.,  52.,  78.,  46.,  63.,  62.,  64.,
        39., 100.,  47.,  70.,  36.,  40.,  74.,  60.,  73.,  90.,  21.,
        77.,  29.,  41.,  66.,  57.,  56.,  76.,  58.,  84.,  38.,  67.,
        31.,  51.,  23.,  72.,  32.,  30.,   0.,  50.,  43.,  35.,  48.,
        42.])

In [73]:
mean_value = df['PROTIME'].mean()
df['PROTIME'] = df['PROTIME'].fillna(mean_value)

In [74]:
df['PROTIME'].unique()

array([ 61.85227273,  80.        ,  75.        ,  85.        ,
        54.        ,  52.        ,  78.        ,  46.        ,
        63.        ,  62.        ,  64.        ,  39.        ,
       100.        ,  47.        ,  70.        ,  36.        ,
        40.        ,  74.        ,  60.        ,  73.        ,
        90.        ,  21.        ,  77.        ,  29.        ,
        41.        ,  66.        ,  57.        ,  56.        ,
        76.        ,  58.        ,  84.        ,  38.        ,
        67.        ,  31.        ,  51.        ,  23.        ,
        72.        ,  32.        ,  30.        ,   0.        ,
        50.        ,  43.        ,  35.        ,  48.        ,
        42.        ])

# HISTOLOGY COLUMN

In [75]:
df['HISTOLOGY'].unique()

array([1, 2])

In [76]:
df['HISTOLOGY'].dtype

dtype('int64')

In [77]:
df['HISTOLOGY'] = df['HISTOLOGY'].astype(str)
df['HISTOLOGY'].dtype

dtype('O')

In [78]:
df['HISTOLOGY'] = df['HISTOLOGY'].replace('1', 'no')
df['HISTOLOGY'] = df['HISTOLOGY'].replace('2', 'yes')
df['HISTOLOGY'].unique()

array(['no', 'yes'], dtype=object)

In [79]:
df.head(50)

Class  AGE     SEX STEROID ANTIVIRALS FATIGUE MALAISE ANOREXIA LIVER_BIG  \
0   LIVE   50    male      no        yes      no     yes      yes        no   
1   LIVE   78    male     yes        yes      no     yes      yes       yes   
2   LIVE   31    male     yes         no     yes     yes      yes       yes   
3   LIVE   34    male     yes        yes     yes     yes      yes       yes   
4   LIVE   34    male     yes        yes     yes     yes      yes       yes   
5    DIE   51    male      no        yes      no     yes       no       yes   
6   LIVE   23    male     yes        yes     yes     yes      yes       yes   
7   LIVE   39    male     yes        yes      no     yes      yes       yes   
8   LIVE   30    male     yes        yes     yes     yes      yes       yes   
9   LIVE   39    male      no         no     yes     yes      yes        no   
10  LIVE   32    male     yes         no      no     yes      yes       yes   
11  LIVE   41    male     yes         no      no     yes      yes       yes   
12  LIVE   30    male     yes        yes      no     yes      yes       yes   
13  LIVE   47    male      no         no     yes     yes      yes       yes   
14  LIVE   38    male      no        yes      no      no       no       yes   
15  LIVE   66    male     yes        yes      no     yes      yes       yes   
16  LIVE   40    male      no        yes      no     yes      yes       yes   
17  LIVE   38    male     yes        yes     yes     yes      yes       yes   
18  LIVE   38    male      no         no     yes     yes      yes        no   
19  LIVE   22  female     yes         no      no     yes      yes       yes   
20  LIVE   27    male     yes        yes      no      no       no        no   
21  LIVE   31    male     yes        yes     yes     yes      yes       yes   
22  LIVE   42    male     yes        yes     yes     yes      yes       yes   
23  LIVE   25  female      no         no     yes     yes      yes       yes   
24  LIVE   27    male      no        yes      no      no      yes       yes   
25  LIVE   49    male      no         no      no      no       no       yes   
26  LIVE   58  female     yes        yes      no     yes      yes       yes   
27  LIVE   61    male      no        yes      no     yes      yes        no   
28  LIVE   51    male      no         no      no      no      yes       yes   
29   DIE   39    male      no         no      no      no      yes       yes   
30   DIE   62    male      no        yes      no      no      yes       yes   
31  LIVE   41  female     yes         no      no      no       no       yes   
32  LIVE   26  female      no        yes     yes     yes      yes       yes   
33  LIVE   35    male     yes        yes      no     yes      yes       yes   
34   DIE   37    male     yes        yes      no     yes      yes       yes   
35  LIVE   23    male     yes        yes      no      no       no       yes   
36  LIVE   20  female      no        yes      no      no       no        no   
37  LIVE   42    male      no        yes     yes     yes      yes       yes   
38  LIVE   65    male     yes        yes      no      no      yes       yes   
39  LIVE   52    male      no         no     yes     yes      yes       yes   
40  LIVE   23    male     yes        yes     yes     yes      yes       yes   
41  LIVE   33    male     yes        yes     yes     yes      yes       yes   
42  LIVE   56    male      no        yes      no     yes      yes       yes   
43  LIVE   34    male     yes        yes     yes     yes      yes       yes   
44  LIVE   28    male     yes        yes      no      no      yes       yes   
45  LIVE   37    male      no        yes     yes     yes      yes       yes   
46  LIVE   28  female     yes        yes      no      no      yes       yes   
47  LIVE   36    male      no        yes     yes     yes      yes       yes   
48  LIVE   38    male     yes         no      no      no       no       yes   
49  LIVE   39    male      no        yes     yes     

# Checking NULL VALUES

In [80]:
df.isnull().sum()

Class               0
AGE                 0
SEX                 0
STEROID             0
ANTIVIRALS          0
FATIGUE             0
MALAISE             0
ANOREXIA            0
LIVER_BIG           0
LIVER_FIRM          0
SPLEEN_PALPABLE     0
SPIDERS             0
ASCITES             0
VARICES             0
BILIRUBIN           0
ALK_PHOSPHATE       0
SGOT                4
ALBUMIN            16
PROTIME             0
HISTOLOGY           0
dtype: int64

In [81]:
df.shape

(154, 20)

CHECKING THE NULL VALUES AFTER COMPLETE PROCESSING THE COLUMNS

In [82]:
df.isna().sum()

Class               0
AGE                 0
SEX                 0
STEROID             0
ANTIVIRALS          0
FATIGUE             0
MALAISE             0
ANOREXIA            0
LIVER_BIG           0
LIVER_FIRM          0
SPLEEN_PALPABLE     0
SPIDERS             0
ASCITES             0
VARICES             0
BILIRUBIN           0
ALK_PHOSPHATE       0
SGOT                4
ALBUMIN            16
PROTIME             0
HISTOLOGY           0
dtype: int64

In [83]:
mean_value = df['ALBUMIN'].mean()
df['ALBUMIN'] = df['ALBUMIN'].fillna(mean_value)

In [84]:
mean_value = df['SGOT'].mean()
df['SGOT'] = df['SGOT'].fillna(mean_value)

In [85]:
df.isna().sum()

Class              0
AGE                0
SEX                0
STEROID            0
ANTIVIRALS         0
FATIGUE            0
MALAISE            0
ANOREXIA           0
LIVER_BIG          0
LIVER_FIRM         0
SPLEEN_PALPABLE    0
SPIDERS            0
ASCITES            0
VARICES            0
BILIRUBIN          0
ALK_PHOSPHATE      0
SGOT               0
ALBUMIN            0
PROTIME            0
HISTOLOGY          0
dtype: int64

In [86]:
df.head(50)

Class  AGE     SEX STEROID ANTIVIRALS FATIGUE MALAISE ANOREXIA LIVER_BIG  \
0   LIVE   50    male      no        yes      no     yes      yes        no   
1   LIVE   78    male     yes        yes      no     yes      yes       yes   
2   LIVE   31    male     yes         no     yes     yes      yes       yes   
3   LIVE   34    male     yes        yes     yes     yes      yes       yes   
4   LIVE   34    male     yes        yes     yes     yes      yes       yes   
5    DIE   51    male      no        yes      no     yes       no       yes   
6   LIVE   23    male     yes        yes     yes     yes      yes       yes   
7   LIVE   39    male     yes        yes      no     yes      yes       yes   
8   LIVE   30    male     yes        yes     yes     yes      yes       yes   
9   LIVE   39    male      no         no     yes     yes      yes        no   
10  LIVE   32    male     yes         no      no     yes      yes       yes   
11  LIVE   41    male     yes         no      no     yes      yes       yes   
12  LIVE   30    male     yes        yes      no     yes      yes       yes   
13  LIVE   47    male      no         no     yes     yes      yes       yes   
14  LIVE   38    male      no        yes      no      no       no       yes   
15  LIVE   66    male     yes        yes      no     yes      yes       yes   
16  LIVE   40    male      no        yes      no     yes      yes       yes   
17  LIVE   38    male     yes        yes     yes     yes      yes       yes   
18  LIVE   38    male      no         no     yes     yes      yes        no   
19  LIVE   22  female     yes         no      no     yes      yes       yes   
20  LIVE   27    male     yes        yes      no      no       no        no   
21  LIVE   31    male     yes        yes     yes     yes      yes       yes   
22  LIVE   42    male     yes        yes     yes     yes      yes       yes   
23  LIVE   25  female      no         no     yes     yes      yes       yes   
24  LIVE   27    male      no        yes      no      no      yes       yes   
25  LIVE   49    male      no         no      no      no       no       yes   
26  LIVE   58  female     yes        yes      no     yes      yes       yes   
27  LIVE   61    male      no        yes      no     yes      yes        no   
28  LIVE   51    male      no         no      no      no      yes       yes   
29   DIE   39    male      no         no      no      no      yes       yes   
30   DIE   62    male      no        yes      no      no      yes       yes   
31  LIVE   41  female     yes         no      no      no       no       yes   
32  LIVE   26  female      no        yes     yes     yes      yes       yes   
33  LIVE   35    male     yes        yes      no     yes      yes       yes   
34   DIE   37    male     yes        yes      no     yes      yes       yes   
35  LIVE   23    male     yes        yes      no      no       no       yes   
36  LIVE   20  female      no        yes      no      no       no        no   
37  LIVE   42    male      no        yes     yes     yes      yes       yes   
38  LIVE   65    male     yes        yes      no      no      yes       yes   
39  LIVE   52    male      no         no     yes     yes      yes       yes   
40  LIVE   23    male     yes        yes     yes     yes      yes       yes   
41  LIVE   33    male     yes        yes     yes     yes      yes       yes   
42  LIVE   56    male      no        yes      no     yes      yes       yes   
43  LIVE   34    male     yes        yes     yes     yes      yes       yes   
44  LIVE   28    male     yes        yes      no      no      yes       yes   
45  LIVE   37    male      no        yes     yes     yes      yes       yes   
46  LIVE   28  female     yes        yes      no      no      yes       yes   
47  LIVE   36    male      no        yes     yes     yes      yes       yes   
48  LIVE   38    male     yes         no      no      no       no       yes   
49  LIVE   39    male      no        yes     yes     

In [87]:
A = pd.DataFrame(df, columns=df.columns)

In [88]:
A

Class  AGE     SEX STEROID ANTIVIRALS FATIGUE MALAISE ANOREXIA LIVER_BIG  \
0    LIVE   50    male      no        yes      no     yes      yes        no   
1    LIVE   78    male     yes        yes      no     yes      yes       yes   
2    LIVE   31    male     yes         no     yes     yes      yes       yes   
3    LIVE   34    male     yes        yes     yes     yes      yes       yes   
4    LIVE   34    male     yes        yes     yes     yes      yes       yes   
..    ...  ...     ...     ...        ...     ...     ...      ...       ...   
149   DIE   46    male     yes        yes      no      no       no       yes   
150  LIVE   44    male     yes        yes      no     yes      yes       yes   
151  LIVE   61    male      no        yes      no      no      yes        no   
152  LIVE   53  female      no        yes      no     yes      yes       yes   
153   DIE   43    male     yes        yes      no     yes      yes       yes   

    LIVER_FIRM SPLEEN_PALPABLE SPIDERS ASCITES  VARICES  BILIRUBIN  \
0          yes             yes     yes     yes      2.0        0.9   
1          yes             yes     yes     yes      2.0        0.7   
2          yes             yes     yes     yes      2.0        0.7   
3          yes             yes     yes     yes      2.0        1.0   
4          yes             yes     yes     yes      2.0        0.9   
..         ...             ...     ...     ...      ...        ...   
149        yes             yes      no      no      1.0        7.6   
150         no             yes     yes     yes      2.0        0.9   
151         no             yes      no     yes      2.0        0.8   
152        yes              no      no     yes      1.0        1.5   
153        yes              no      no      no      2.0        1.2   

     ALK_PHOSPHATE   SGOT  ALBUMIN    PROTIME HISTOLOGY  
0            135.0   42.0      3.5  61.852273        no  
1             96.0   32.0      4.0  61.852273        no  
2             46.0   52.0      4.0  80.000000        no  
3             85.0  200.0      4.0  61.852273        no  
4             95.0   28.0      4.0  75.000000        no  
..             ...    ...      ...        ...       ...  
149           85.0  242.0      3.3  50.000000       yes  
150          126.0  142.0      4.3  61.852273       yes  
151           75.0   20.0      4.1  61.852273       yes  
152           81.0   19.0      4.1  48.000000       yes  
153          100.0   19.0      3.1  42.000000       yes  

[154 rows x 20 columns]

# TRAIN AND TEST

In [89]:
from sklearn.model_selection import train_test_split

In [90]:
len(A)

154

In [91]:
train,test = train_test_split(A)

In [92]:
len(train)

115

In [93]:
len(test)

39

# TRANSFORMATION TECHNIQUE

In [94]:
from sklearn.preprocessing import StandardScaler

In [104]:
scaler = StandardScaler()

In [98]:
df.head()

Class  AGE   SEX STEROID ANTIVIRALS FATIGUE MALAISE ANOREXIA LIVER_BIG  \
0  LIVE   50  male      no        yes      no     yes      yes        no   
1  LIVE   78  male     yes        yes      no     yes      yes       yes   
2  LIVE   31  male     yes         no     yes     yes      yes       yes   
3  LIVE   34  male     yes        yes     yes     yes      yes       yes   
4  LIVE   34  male     yes        yes     yes     yes      yes       yes   

  LIVER_FIRM SPLEEN_PALPABLE SPIDERS ASCITES  VARICES  BILIRUBIN  \
0        yes             yes     yes     yes      2.0        0.9   
1        yes             yes     yes     yes      2.0        0.7   
2        yes             yes     yes     yes      2.0        0.7   
3        yes             yes     yes     yes      2.0        1.0   
4        yes             yes     yes     yes      2.0        0.9   

   ALK_PHOSPHATE   SGOT  ALBUMIN    PROTIME HISTOLOGY  
0          135.0   42.0      3.5  61.852273        no  
1           96.0   32.0      4.0  61.852273        no  
2           46.0   52.0      4.0  80.000000        no  
3           85.0  200.0      4.0  61.852273        no  
4           95.0   28.0      4.0  75.000000        no

In [106]:
numeric_columns = ['VARICES', 'BILIRUBIN', 'ALK_PHOSPHATE', 'SGOT', 'ALBUMIN', 'PROTIME']
scaler = StandardScaler()
B = scaler.fit_transform(A[numeric_columns])

# Convert the scaled array back to a DataFrame
B_df = pd.DataFrame(B, columns=numeric_columns)

In [112]:
pd.DataFrame(B).describe()

0             1             2             3             4  \
count  1.540000e+02  1.540000e+02  1.540000e+02  1.540000e+02  1.540000e+02   
mean  -2.768348e-16 -2.306957e-17  4.613914e-17  1.153478e-17 -1.084270e-15   
std    1.003263e+00  1.003263e+00  1.003263e+00  1.003263e+00  1.003263e+00   
min   -2.748737e+00 -9.516813e-01 -1.606989e+00 -8.192493e-01 -2.783033e+00   
25%    3.638034e-01 -5.307344e-01 -5.020892e-01 -6.040944e-01 -5.124165e-01   
50%    3.638034e-01 -3.623556e-01 -3.533527e-01 -3.040100e-01  1.363310e-01   
75%    3.638034e-01  5.859126e-02  3.850179e-01  1.489476e-01  6.228916e-01   
max    3.638034e-01  5.530901e+00  4.108743e+00  6.360128e+00  4.191003e+00   

                  5  
count  1.540000e+02  
mean   4.613914e-17  
std    1.003263e+00  
min   -3.597416e+00  
25%   -2.822151e-01  
50%    0.000000e+00  
75%    2.121570e-01  
max    2.218726e+00

#MinMax Scaler


In [108]:
from sklearn.preprocessing import MinMaxScaler

In [109]:
scaler = MinMaxScaler()

In [111]:
numeric_columns = ['VARICES', 'BILIRUBIN', 'ALK_PHOSPHATE', 'SGOT', 'ALBUMIN', 'PROTIME']
scaler = StandardScaler()
B = scaler.fit_transform(A[numeric_columns])

# Convert the scaled array back to a DataFrame
B_df = pd.DataFrame(B, columns=numeric_columns)

In [113]:
pd.DataFrame(B).describe()

0             1             2             3             4  \
count  1.540000e+02  1.540000e+02  1.540000e+02  1.540000e+02  1.540000e+02   
mean  -2.768348e-16 -2.306957e-17  4.613914e-17  1.153478e-17 -1.084270e-15   
std    1.003263e+00  1.003263e+00  1.003263e+00  1.003263e+00  1.003263e+00   
min   -2.748737e+00 -9.516813e-01 -1.606989e+00 -8.192493e-01 -2.783033e+00   
25%    3.638034e-01 -5.307344e-01 -5.020892e-01 -6.040944e-01 -5.124165e-01   
50%    3.638034e-01 -3.623556e-01 -3.533527e-01 -3.040100e-01  1.363310e-01   
75%    3.638034e-01  5.859126e-02  3.850179e-01  1.489476e-01  6.228916e-01   
max    3.638034e-01  5.530901e+00  4.108743e+00  6.360128e+00  4.191003e+00   

                  5  
count  1.540000e+02  
mean   4.613914e-17  
std    1.003263e+00  
min   -3.597416e+00  
25%   -2.822151e-01  
50%    0.000000e+00  
75%    2.121570e-01  
max    2.218726e+00

# BINARIZER TECHNIQUE

In [114]:
from sklearn.preprocessing import Binarizer

In [115]:
bin = Binarizer(threshold=0.5)

In [116]:
B = bin.fit_transform(B)

In [117]:
pd.DataFrame(B)

0    1    2    3    4    5
0    0.0  0.0  1.0  0.0  0.0  0.0
1    0.0  0.0  0.0  0.0  0.0  0.0
2    0.0  0.0  0.0  0.0  0.0  1.0
3    0.0  0.0  0.0  1.0  0.0  0.0
4    0.0  0.0  0.0  0.0  0.0  1.0
..   ...  ...  ...  ...  ...  ...
149  0.0  1.0  0.0  1.0  0.0  0.0
150  0.0  0.0  1.0  1.0  1.0  0.0
151  0.0  0.0  0.0  0.0  0.0  0.0
152  0.0  0.0  0.0  0.0  0.0  0.0
153  0.0  0.0  0.0  0.0  0.0  0.0

[154 rows x 6 columns]

In [120]:
df.columns

Index(['Class', 'AGE', 'SEX', 'STEROID', 'ANTIVIRALS', 'FATIGUE', 'MALAISE',
       'ANOREXIA', 'LIVER_BIG', 'LIVER_FIRM', 'SPLEEN_PALPABLE', 'SPIDERS',
       'ASCITES', 'VARICES', 'BILIRUBIN', 'ALK_PHOSPHATE', 'SGOT', 'ALBUMIN',
       'PROTIME', 'HISTOLOGY'],
      dtype='object')

Linear Regression Model

In [121]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score

# Assuming 'data' is your DataFrame with columns 'VARICES', 'BILIRUBIN', etc., and 'CLASS' as the target variable
X =df[['VARICES', 'BILIRUBIN', 'ALK_PHOSPHATE', 'SGOT', 'ALBUMIN', 'PROTIME']]
y =df['Class']

# Encode categorical target variable
le = LabelEncoder()
y = le.fit_transform(y)

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Regression Model
reg_model = LogisticRegression()
reg_model.fit(X_train, y_train)
y_pred_reg = reg_model.predict(X_test)
acc_reg = accuracy_score(y_test, y_pred_reg)

# Naïve Bayes Model
nb_model = GaussianNB()
nb_model.fit(X_train, y_train)
y_pred_nb = nb_model.predict(X_test)
acc_nb = accuracy_score(y_test, y_pred_nb)

print(f"Logistic Regression Accuracy: {acc_reg}")
print(f"Naïve Bayes Accuracy: {acc_nb}")


Logistic Regression Accuracy: 0.8297872340425532
Naïve Bayes Accuracy: 0.723404255319149
